name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Run ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: make lint

      - name: Run Prettier
        run: make format

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}